# Global configuration options. The `queue_ahead` and `tz` options can also be set on each task.
queue_ahead: 20160 # Number of minutes to queue jobs into the future
queue_name: "default" # The Sidekiq queue name used by SimpleScheduler::FutureJob
tz: "Europe/Berlin" # The application time zone will be used by default if not set

weekly_task:
  class: "WeeklyJob"
  every: "30.seconds"
  at: "**:00"